services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    environment:
      - SYMFONY_ENV=dev
    depends_on:
      - db
    networks:
      - symfony

  web:
    image: nginx:alpine
    container_name: symfony_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony

  db:
    image: postgres:17
    container_name: nfq-shop
    environment:
      POSTGRES_DB: nfq_shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  pgdata:
    driver: local
