<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20241024114919 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add items table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, sell_in INT NOT NULL, quality INT NOT NULL, img_url VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE items');
    }
}
